# Clippy configuration
msrv = "1.75.0"
warn-on-all-wildcard-imports = true
allow-expect-in-tests = true
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true
disallowed-methods = [
    { path = "std::io::stdout", reason = "Use tracing instead" },
    { path = "std::io::stderr", reason = "Use tracing instead" },
    { path = "println", reason = "Use tracing instead" },
    { path = "eprintln", reason = "Use tracing instead" },
    { path = "dbg", reason = "Use tracing instead" },
]